### ISSUE TITLE
Big data input support

### ISSUE THREAD

**Issue by marekbatelka** [jeremysanders/veusz#101]
Hello, loving Veusz.
I have dataset of 100 000+ rows and 350 colums.
Veusz is crashing on import. 

Any idea how to support this?
Thank you
Marek

**Comment by jeremysanders** [comment]
What does it say when it crashes? Is it a MemoryError? Is this Windows, Linux or Mac?

Veusz is only compiled with 32 bit support on Windows, so it's possible that it's hitting a memory limit. I would have thought 100000 x 350 x 8 bytes should be ok, although there may be some temporary copies somewhere in the code.

**Comment by marekbatelka** [comment]
Hi Jeremy,
thank you for reply and sorry for delay in mine.

This might be indeed memory issue as I was running 32 bit windows machine. 
You can close this issue.
