### ISSUE TITLE
Compute function wrong

### ISSUE THREAD

**Issue by tesfel** [jeremysanders/veusz#102]
Hello,
I'm using Veusz v1.22 with linux. I want to calculate the mean of dataset, but obvious Veusz calculation function is wrong. When I calculate the mean value of the dataset which is 1,2,3,4,5,6 Veusz says the mean value is 1. How can I fix that?

**Comment by jeremysanders** [comment]
Can you better explain the steps you're using to get the mean? Is this using one of the dataset operations, creating a dataset via a function or just using the dataset browser?

**Comment by tesfel** [comment]
Thanks for your quick reply!
I import data from a CSV file. (Data -> Import -> select file [...] -> Import) The file is correctly imported. To calculate the mean/average of a dataset I select Data -> Operation -> Compute -> Mean of datasets. I choose one dataset and name the output dataset.

**Comment by jeremysanders** [comment]
That operation doesn't compute the mean of a single dataset. It creates a mean dataset of several different datasets. If you give it a single dataset, you'll get the same dataset out.

**Comment by tesfel** [comment]
Is there any possibility to calculate the mean of a single dataset with Veusz?

**Comment by jeremysanders** [comment]
You could either create a datset using an expression (Data->Create), or use directly when plotting (enter in the dataset name box), something like [mean(foo)], where foo is your dataset name. This will give you a single-item dataset containing the mean of foo.

**Comment by tesfel** [comment]
Thanks!
