### ISSUE TITLE
How to fill between two lines or emulate error region?

### ISSUE THREAD

**Issue by brunetto** [jeremysanders/veusz#107]
Hi!
I need to create an error strip instead of using multiple errorbars.
Is there a way to do this?

I thought about this two possibilities:

1. "fill between" option in the fill tab to fill between two `xy` lines corresponding to `+err` `-err` (made by hand, not `+/-err` in the dataset, or drown from the corresponding `+/-err`, it is the same to me)*
2. have the "error strip" option in the error bar tab

(*) I try to explain better: I can fill between to xy widget created from two 1d dataset I created on my own to reproduce the error, or I can create a fill between the error associated to the dataset I'm plotting

**Comment by jeremysanders** [comment]
I don't understand what you mean by error strip. There's already an option to create a filled region for error bars as the "Error style" option for the plotting widget.

**Comment by brunetto** [comment]
Ok, I haven't saw it because I was looking for it in the errorbar tab, not in the main tab. 
Is there a way to change the upper and lower fill of the shaded region corresponding to the errors?

**Comment by jeremysanders** [comment]
Yes - it's the same settings as the Fill Above/Below settings (the rightmost tabs of the formatting panel)
