### ISSUE TITLE
Veusz fails to remember window layout and restarts from a default layout everytime

### ISSUE THREAD

**Issue by badshah400** [jeremysanders/veusz#108]
I am using veusz 1.22 compiled with python 3.4 on openSUSE 13.2. I noticed that the veusz window has recently (I can't remember from which version, but if want me to git bisect, I will) started reverting to a default layout every time when it starts. I prefer having the Formatting widget docked on the right, just above the Data widget, and do so immediately when I start veusz. I expect it to remember this layout, and veusz used to do so until recently (probably until version 1.20). Now, because it restores to a default layout upon every start-up, I have to do this exercise of setting up the window the way I prefer it every time, which is inconvenient. The image shows comparison of veusz windows "before" I close it (I have set it up so the formatting widget is on the right and the widgets are also wider) and then "after" closing this window and starting veusz again, where it has gone back to its default layout. It would help a lot if veusz could just remember its layout when closed and resume from the same upon restart.

Thanks a lot for the great application.

![veusz-comparison](https://cloud.githubusercontent.com/assets/3532467/7100240/a1733a1c-dfe2-11e4-986e-123b4b60c895.png)

**Comment by jeremysanders** [comment]
I don't think anything has changed in the source code recently. You could try deleting or renaming your ~/.config/veusz.org/veusz.conf file to see whether that fixes the problem.

**Comment by badshah400** [comment]
I have tried that (once more just now to check), doesn't help...

**Comment by jeremysanders** [comment]
Ok - I think the problem must be related to Python 3 - I can see the problem if I use that instead of Python 2. Thanks for the report - I'll try to work out what is happening.

**Comment by badshah400** [comment]
I just checked, indeed the version built with python 2 works correctly, the layout doesn't revert to its default all the time.

**Comment by jeremysanders** [comment]
This commit appears to fix the problem. I'll include it in the upcoming release. THanks again for the report.

**Comment by badshah400** [comment]
Yes, that does it. Thanks a lot.
