### ISSUE TITLE
Artifacts when using log axes?

### ISSUE THREAD

**Issue by brunetto** [jeremysanders/veusz#110]
Hi!
I have this two results when showing the same plot with y axis linear or log: 

![profilesplotlinear](https://cloud.githubusercontent.com/assets/1931614/7142986/e95ebfac-e2dc-11e4-900c-66a84462685d.png)
![profilesplotlog](https://cloud.githubusercontent.com/assets/1931614/7142987/e9645bec-e2dc-11e4-8515-ec949152fb9a.png)

May the horizontal line be an artifact due to log(0)=-infinity? How can I avoid it?

**Comment by jeremysanders** [comment]
Weird - it should handle zeros. Can you upload an example?

**Comment by jeremysanders** [comment]
A workaround may be to plot clip(myfunc, 1e-7, 1)

**Comment by brunetto** [comment]
What example can help?
This plot was entirely made from the GUI and two 1D dataset... can I still add clip somewhere?

**Comment by jeremysanders** [comment]
Is it possible to upload somewhere or email me the vsz file?

**Comment by jeremysanders** [comment]
Hi Brunetto. This commit appears to fix the problem. It's quite big and requires recompilation. I had to clip the points to a box around the graph before fitting the bezier curve, to avoid the fitting breaking down.

**Comment by brunetto** [comment]
I pulled and recompiled. 
Then:

```bash
$ sudo python setup.py install
running install
running build
running build_py
running build_ext
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/local/bin/veusz_listen to 755
changing mode of /usr/local/bin/veusz to 755
running install_data
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/veusz-1.22.999.egg-info
Writing /usr/local/lib/python2.7/dist-packages/veusz-1.22.999.egg-info
```
Despite this I obtain

```
$ /usr/local/bin/veusz --version
Veusz 1.22.99

Copyright (C) Jeremy Sanders 2003-2015 <jeremy@jeremysanders.net> and contributors
Licenced under the GNU General Public Licence (version 2 or greater)
```

I tried again and I obtain version `1.15`.

Then I tried with a fresh clone, build and install and again I have `Finished processing dependencies for veusz==1.22.999` but the version is 1.15v.

I also checked 

```
cat /usr/local/bin/veusz
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'veusz==1.22.999','gui_scripts','veusz'
__requires__ = 'veusz==1.22.999'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('veusz==1.22.999', 'gui_scripts', 'veusz')()
    )
```

What am I missing?

**Comment by jeremysanders** [comment]
Do you mean you get 1.15 when you run the program? Do you have a veusz package installed on your system? You may need to remove this or make sure that the /usr/local/lib/python2.7/dist-packages is on the python path first (you can try setting the PYTHONPATH environment directory to that directory).

**Comment by brunetto** [comment]
You were right.. I had an older version installed through the package manager... it didn't showed up before...

Now I can confirm that the last version is working.

Thanks!!
