### ISSUE TITLE
Proposal: reload from vsz file

### ISSUE THREAD

**Issue by brunetto** [jeremysanders/veusz#111]
Hi!
I don't think this is already possible. And I don't think how difficult can be to implement.
Sometime it would be useful to be able, from the GUI, to reload the document from the veusz file.
This necessity can rise when modifying the file by hand or from script while monitoring what happens.
Now, instead, it is necessary to close and reopen the GUI.

**Comment by Sembazuru** [comment]
This functionality would also be handy when experimenting with settings in the GUI. A re-open file would provide an easy way to go back to a known good point without closing and re-opening (think of a gaming analogy of a 'save-point').

**Comment by jeremysanders** [comment]
It wouldn't be too hard to implement.

**Comment by jeremysanders** [comment]
I've implemented a reload menu option. This will be in the next release.
