### ISSUE TITLE
Can't import multidimensional data from HDF5

### ISSUE THREAD

**Issue by flinz** [jeremysanders/veusz#114]
Hi,

I am trying to import data from a HDF5. However, the only parts of my dataset I seem to be able to import are the 1 dimensional ones. All higher dimensional data are unselectable.

In the screenshot below I clicked the general import, note that only the 1D element is being selected.
![image](https://cloud.githubusercontent.com/assets/97735/7388249/14297370-ee64-11e4-8e7e-05210511f356.png)

Is this a missing feature or am I missing something? :)

**Comment by jeremysanders** [comment]
Veusz only supports 1D (with optional error bars) and 2D datasets internally. To import a higher dimensional dataset you need to enter a slice to convert to 1D. For example you can enter a slice like "1,1,:" to import a 800-sized array from shape_std.
