### ISSUE TITLE
Unsaved Histogram datasets

### ISSUE THREAD

**Issue by AnthonyBesq** [jeremysanders/veusz#115]
Using Histogram module (Veusz 1.23 on mac Yosemite OSX), I obtain correct datasets to plot an histogram.
When the file is saved, closed, and then reopened, position and height datasets are no more available. 
Have I missed something ?

**Comment by jeremysanders** [comment]
You're correct, unfortunately. There appears to be a bug in the latest version. I'll see whether I can work out what's happening.

**Comment by jeremysanders** [comment]
Thanks for the report. The bug is now fixed in the commit above. It was due to some simplification of the dataset code in 1.23.
