### ISSUE TITLE
is this an issue? read in data not as expected

### ISSUE THREAD

**Issue by bsmile001** [jeremysanders/veusz#120]
The following saved in a file cannot be correctly read in. I expect it to skip the first line, and then read the 2nd and 3rd number as x,y coordinate. But VEUSZ does not do as expected. Help please!

(ref:BCC)
SC   3.16872427983539e+000   -6.12337765115543e+000

**Comment by jeremysanders** [comment]
The Veusz importing doesn't work like this. The default import mode reads columns of data, separated by whitespace. It can optionally ignore non-numeric lines. This data doesn't look like this.

However, you could try the CSV import mode. Tell it to skip 1 row at the top of the file and change the column delimiter to {space}.
