### ISSUE TITLE
axis-function breaks BoxShape alignement by axis

### ISSUE THREAD

**Issue by mythsmith** [jeremysanders/veusz#123]
If an axis-function is used as position X/Y axis for any BoxShape widget, its updateControlItem will not work anymore.

Seems a non-array object is passed to AxisFunction._linearInterpolWarning.
```
Traceback (most recent call last):
  File "/opt/veusz/widgets/controlgraph.py", line 88, in mouseReleaseEvent
    self.parentItem().updateWidget()
  File "/opt/veusz/widgets/controlgraph.py", line 464, in updateWidget
    self.params.widget.updateControlItem(self.params)
  File "/opt/veusz/widgets/shape.py", line 165, in updateControlItem
    cgi.posn[0], cgi.posn[1])
  File "/opt/veusz/widgets/plotters.py", line 262, in _getGraphCoords
    ypos = axes[1].plotterToDataCoords(posn, yplt)
  File "/opt/veusz/widgets/axis.py", line 604, in plotterToDataCoords
    return scale * self.plotterToGraphCoords(bounds, vals)
  File "/opt/veusz/widgets/axisfunction.py", line 536, in plotterToGraphCoords
  File "/opt/veusz/widgets/axisfunction.py", line 513, in _linearInterpolWarning
    if any(vals < xcoords[0]) or any(vals > xcoords[-1]):
TypeError: 'numpy.bool_' object is not iterable
```

**Comment by jeremysanders** [comment]
Sorry for the delay. This was fixed in
https://github.com/jeremysanders/veusz/commit/4abccc2539ae9d8b2b33ed52fb210e1768eb877c

**Comment by mythsmith** [comment]
Thanks!

Il 11 agosto 2015 16:14:47 CEST, Jeremy Sanders <notifications@github.com> ha scritto:

Sorry for the delay. This was fixed in
4abccc2<https://github.com/jeremysanders/veusz/commit/4abccc2539ae9d8b2b33ed52fb210e1768eb877c>

—
Reply to this email directly or view it on GitHub<https://github.com/jeremysanders/veusz/issues/123#issuecomment-129897622>.

--
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

watzip

________________________________

===========================================================
The information in this email is confidential, and is intended solely for the addressee(s).
Access to this email by anyone else is unauthorized and therefore prohibited. If you are
not the intended recipient you are notified that disclosing, copying, distributing or taking
any action in reliance on the contents of this information is strictly prohibited and may be unlawful.
===========================================================
