### ISSUE TITLE
Cannot create freezed exe on windows

### ISSUE THREAD

**Issue by mythsmith** [jeremysanders/veusz#131]
Steps top reproduce:
 ```
pyinstaller -y veusz_windows_pyinst.spec
```
This fails because glob module is not imported (see pull request #127). After fixing that, pyinstaller succeeds. Will create dirs build, dist. 

By executing dist\veusz_main\veusz.exe, displays a message box showing:
```
Fatal Error! 
veusz_main returned -1
```
No debug message is printed on the console.

Is this spec file up-to-date? Can you provide more details about how you are building freezed packages?

**Comment by jeremysanders** [comment]
The spec file is exactly what I'm using. I don't have an import for glob and it worked fine. Maybe my pyinstaller installation is somehow importing glob into its namespace.
