### ISSUE TITLE
Memory leak on slow version of plotClippedPolyline

### ISSUE THREAD

**Issue by riccardomarotti** [jeremysanders/veusz#132]
Adding points to a plot causes a growing memory consumption, leading to application crash.
Fortunately, this does not happen when using fast routines implemented in c++, so this isn't a big issue.

Our investigation led to `plotClippedPolyline` as a probable culprit (in `/veusz/utils/slowfuncs.py`).

**Comment by jeremysanders** [comment]
Interesting - I can't reproduce this calling the function in a simple loop. If this function is at fault, it looks to be a PyQt bug, which may have been fixed in later versions.

**Comment by mythsmith** [comment]
You can close it: it's gone long ago.
