### ISSUE TITLE
box plots with calculate = False not drawing

### ISSUE THREAD

**Issue by djmannion** [jeremysanders/veusz#133]
I've been having trouble with box plots with manual values (i.e. calculate = False) not drawing. The axis range updates, but nothing is displayed.

I think I might have pinned it down to this line in `boxplot.py` (#408, currently):
```python
if N.any((d is None for d in datasets)):
    return
```
It seems like this will always be followed because the ``any`` will return a generator.

The box plots are drawn correctly if I replace it with:
```python
if N.any([d is None for d in datasets]):
    return
```

**Comment by jeremysanders** [comment]
Thanks for the report. I've fixed this by switching to python's any, rather than using numpy's.I think this is a bug in numpy.

**Comment by jeremysanders** [comment]
This looks related to this: https://github.com/numpy/numpy/issues/6555
