### ISSUE TITLE
FieldWidget becomes unusable with complex widget hierarchies

### ISSUE THREAD

**Issue by mythsmith** [jeremysanders/veusz#134]
The FieldWidget class used in plugins definition will list all widgets by their name, without any order or hierarchy. 
If two widgets have the same name, but on different pages (for example), there will be no way to distinguish them.
For example, if we have two pages, with two graphs, with two xy plots with the same name, it will be impossible to distinguish them in a FieldWidget.

**Comment by jeremysanders** [comment]
The above patch adds a tooltip showing the full path, which should distinguish the entries
