### ISSUE TITLE
Malware detected on Veusz Windows installer - Trojan:Win32/Varpes.L!plock

### ISSUE THREAD

**Issue by acelere** [jeremysanders/veusz#143]
Team, I have installed veusz from file veusz-1.23.2-windows-setup.exe and windows defender has shown a message saying that the file is compromised with malware "Trojan:Win32/Varpes.L!plock" .

Please check.

Thanks.

**Comment by jeremysanders** [comment]
I didn't find any problems on my system with this file when I run a defender scan (using Windows 7). The signature of the file verifies correctly for me too, so it doesn't seem to be modified.

Did you download the file from the main website, i.e. http://home.gna.org/veusz/downloads/ or http://download.gna.org/veusz/Binaries-Windows/ ?  Are you sure that your system is clean?

**Comment by acelere** [comment]
Hi, I downloaded it from
download.gna.org/veusz/Binaries-Windows/veusz-1.2.3.2-windows-setup.exe
I ran defender full scan now and it is clean.
Anyway, if you checked the file signatures, it might have been something
else here in my computer. I just wanted to warn quickly before a real
problem occurs.
Thanks for the response and checking.
Let's close the issue.

**Comment by mondaysunrise** [comment]
Reopening: For current Windows download, VirusTotal flags as malware: https://www.virustotal.com/graph/embed/g366e923f27ce48478870beddce36a23f838ec67950424d919282f1f52b00aee8

What is going on?
