### ISSUE TITLE
[python3] crash when right clicking on a selection of datasets

### ISSUE THREAD

**Issue by KDB2** [jeremysanders/veusz#156]
Hi Jeremy,

If you start Veusz with python3, and create several datasets, then select these datasets and right-click on them, Veusz is crashing. 

Here is the error message: 
Traceback (most recent call last):
  File ".../veusz/qtwidgets/datasetbrowser.py", line 484, in showContextMenu
    types = utils.unique([ type(n) for n in nodes ])
  File ".../veusz/utils/utilfuncs.py", line 468, in unique
    inlist.sort()
TypeError: unorderable types: type() < type()

If I understand correctly, it seems to come from the fact that python3 has no cmp parameter in sort. 
http://python3porting.com/differences.html#sorting

I have not found any easy fix, but I implemented a dedicated sorting function and it seems to work. Not really elegant but working. 

def unique(inlist):
    """Get unique entries in list."""

    def sortAlg(inlist):
        """Sorting algorithm for unique"""
        names = [str(item) for item in inlist]
        rank = N.array(names).argsort().argsort()
        sortRes = [None] * len(names)
        for rk, item in czip(rank, inlist):
            sortRes[rk] = item
        return sortRes

    inlist = list(inlist)
    # inlist.sort()
    inlist = sortAlg(inlist)

If you find an easier way, I would be glad to hear about it.

Emmanuel

**Comment by KDB2** [comment]
More simply,

    inlist = list(inlist)
    names = N.array([str(item) for item in inlist])
    inlist = list(N.array(inlist)[names.argsort()])

**Comment by jeremysanders** [comment]
Sorry for the delay. I hope this fixes the bug.

**Comment by KDB2** [comment]
Hello Jeremy,

Your fix is perfect and really elegant. Thanks a lot!
