### ISSUE TITLE
help() command causes veusz to freeze

### ISSUE THREAD

**Issue by mythsmith** [jeremysanders/veusz#157]
If you run the help() python function in the console window, veusz will freeze. This might happen with any other interactive command.
One simple approach would be to simply filter out the help() command. But this seems not quite general. Maybe a timeout and a separate execution thread?

**Comment by KDB2** [comment]
I can confirm the freeze with Python2. 
I don't see it with python3.

Could you please confirm your configuration?

**Comment by mythsmith** [comment]
Python2 also for me.

**Comment by jeremysanders** [comment]
I don't see this either on Python 2. What command are you doing help on?

It could be the pager. You could try something like:
>>> import pydoc
>>> pydoc.pager = pydoc.plainpager

(see http://stackoverflow.com/questions/26194684/how-to-disable-python-shell-spawning-less-with-help)

**Comment by KDB2** [comment]
I tried with the 2 commands given above but it's still freezing with python2.
In the console I type help() and the software is completely frozen. 

With Python3, I get some text and then I have the control again.

**Comment by jeremysanders** [comment]
Ok, it's due to veusz not replacing the stdin stream. Now it's a file object which just raises an exception.

It would be nice to allow proper input, but I'm not sure how this can be achieved.

**Comment by KDB2** [comment]
The fix is working for me. Thanks.

**Comment by mythsmith** [comment]
Works, thanks!
