### ISSUE TITLE
Export to EMF crashes

### ISSUE THREAD

**Issue by Mesyanzhin** [jeremysanders/veusz#165]
Hello!

I'm trying to use the module emf_export.py from your project Veusz. I'm writing an application in Windows7 64-bit, using Python 2.7.11 32-bit and PyQt 4.11.4
Here is my code:

```
from PyQt4 import QtGui
import emf_export
# anything

class AnyClass(QtGui.QGraphicsScene):
    # anything

    def exportEmf(self, filename):
        emfdevice = emf_export.EMFPaintDevice(self.width(), self.height())
        painter = QtGui.QPainter(emfdevice)
        self.render(painter)
        painter.end()
        emfdevice.engine.saveFile(filename)
```

When I try to call this method with some drawings in scene, the program crashes, instead Traceback in console issued the following text:

> QPainter::begin: Paint device returned engine == 0, type: 2
> QPainter::setRenderHint: Painter must be active to set rendering hints
> QPainter::setRenderHint: Painter must be active to set rendering hints
> QPainter::setWorldTransform: Painter not active
> QPainter:: end: Painter not active, aborted
> Qt has caught an exception thrown from an event handler. Throwing
> exceptions from an event handler is not supported in Qt. You must
> reimplement QApplication::notify() and catch all exceptions there.
> 
> Fatal Python error: PyEval_RestoreThread: NULL tstate
> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.
> 
> Process finished with exit code 255

Please tell me what I might be doing wrong?

**Comment by mythsmith** [comment]
This definitely seems something arising from an incorrect use of QPainter. Probably a call to painter.begin(emfdevice) would do.
And also you should probably use Veusz's DirectPainter instead of QPainter, like in https://github.com/jeremysanders/veusz/blob/master/veusz/document/export.py#L389. 
I cannot test these hints on Linux.

**Comment by Mesyanzhin** [comment]
I replaced the line
`        emfdevice = emf_export.EMFPaintDevice(self.width(), self.height())`
on the lines
```
        dpi = 90.0
        emfdevice = emf_export.EMFPaintDevice(self.width()/dpi, self.height()/dpi, dpi=dpi)
```
and everything worked properly.
Thank you!
