### ISSUE TITLE
Question/Proposal: csv import precision

### ISSUE THREAD

**Issue by H2OBrain** [jeremysanders/veusz#171]
Hello,
To import our logfiles it would be nice to have a higher significant digit precision in the csv importer.
In our file we want to look for example at a time range of 1000000 to 1000001 s. This is currently rounded to 6 digits to we get 1000000 to 1000000.
Is Veusz using single precision floats internally? So if higher precision is not possible, is there maybe already a way to modify the offset during the file import?

**Comment by jeremysanders** [comment]
Sorry - I can't reproduce your problem. I tried importing those numbers and it didn't round anything. The Data->Edit dialog box, however, rounds numbers for display, but they're not rounded internally or when plotted.

**Comment by H2OBrain** [comment]
Ups, yeah thanks, sorry to bother you with this. Our problem was actually the other way around (no rounding).
I tried to fix a colleagues problem and thought the imported data was invalid. We looked at the data in the Edit dialog box. It would probably be nice if the edit dialog box rounding was configurable..
