### ISSUE TITLE
Variable text control in labels

### ISSUE THREAD

**Issue by alk224** [jeremysanders/veusz#172]
Would like control over which parts of the label are italicized or not. Probably applicable to others who have additional text requirements. The below image represents data replotted from [Hubert and Gehring, 2008](https://www.ncbi.nlm.nih.gov/pubmed/18685872). The third category (Rhizopogon vulgaris) is a binomial latin name, thus should be italicized. Pezizales is order-level taxonomy, and Thelephoraceae is family-level, so neither should be italicized. Tomentella sp. includes genus, but not confident speces. "Tomentella" should be italicized, but not "sp." Aside from this little issue, Veusz is super great!

![image](https://cloud.githubusercontent.com/assets/4246886/23873073/060f0ad4-07ee-11e7-92c0-175b53c91de4.png)

**Comment by jeremysanders** [comment]
Hi - this is already possible. You can include LaTeX-style markup in your text. You can write, for example,

\italic{some italic text} some normal text \bold{some bold text}

See the instruction manual for details.

Jeremy
