### ISSUE TITLE
X-axis values not matching to actual values.

### ISSUE THREAD

**Issue by g-sob** [jeremysanders/veusz#174]
When plotting a simple xy graph the values shown in x-axis are always a few units below actual values (seven unities in some cases, 20 unities in others).

**Comment by jeremysanders** [comment]
Please provide an example.

**Comment by g-sob** [comment]
Dear Jeremy,

Firstly, congrats for your program. It has been very useful and the quality
of the graphs it makes is very nice.

Take a look at the pictures below. The point 157.1 x 846.0, as well as the
whole curve, is slightly displaced to the left. That happened before in
another graph with a much greater shift.

[image: Imagem inline 1]
[image: Imagem inline 2]

Guilherme Augusto N. Sobrinho

MSc. em Radioecologia - IRD/CNEN
Engenheiro Agrônomo - UFRuralRJ
(+55 21) 9 9324-9141 / 98913-5031
skype: guilherme-sobrinho
--
MSc. Tropical Radioecology
BSc. Agronomy

2017-04-18 14:07 GMT-03:00 Jeremy Sanders <notifications@github.com>:

**Comment by jeremysanders** [comment]
Thanks, but the images are missing. Can you also provide the vsz file (or a simplified version)?

THanks
Jeremy

**Comment by g-sob** [comment]
That's weird... Ok, Please see the attachment.

Thank you very much for the support.




Guilherme Augusto N. Sobrinho

MSc. em Radioecologia - IRD/CNEN
Engenheiro Agrônomo - UFRuralRJ
(+55 21) 9 9324-9141 / 98913-5031
skype: guilherme-sobrinho
--
MSc. Tropical Radioecology
BSc. Agronomy

2017-04-18 14:32 GMT-03:00 Jeremy Sanders <notifications@github.com>:

**Comment by jeremysanders** [comment]
Sorry - there's still no file. Does it work if you attach on the website rather than by email?

**Comment by g-sob** [comment]
Dear Jeremy, I apologize for the delay in answering you. Unfortunately, I couldn't attach the veusz file. Apparently GitHub "doesn't support that file type". Not even zipped.
Let's see if now it works.

![image](https://cloud.githubusercontent.com/assets/27735649/25236602/a5bb546e-25be-11e7-87fa-6a4351594baf.png)
[Bug Veuz data.xlsx](https://github.com/jeremysanders/veusz/files/943680/Bug.Veuz.data.xlsx)
![bug veusz](https://cloud.githubusercontent.com/assets/27735649/25236276/dd5122d8-25bd-11e7-8439-185e084d3ec9.jpg)

**Comment by jeremysanders** [comment]
Ok - I imported this as CSV and noticed A and B have different lengths. This is because there is some missing data in the middle of the file. By default Veusz skips missing data - this may be why you're not seeing the data you expect. If you go to the Data->Edit dialog box, and select both A and B together, then you can see what Veusz thinks it is plotting.

If this is the problem, trying using the "Treat blanks as data values" options when importing CSV data, or you can use "nan" to mark empty values.

**Comment by g-sob** [comment]
Hey, Jeremy! I apologize for taking so long to give you this feedback. Yep, now it works perfectly. I filled the empty cells with "nan" and voilà. Take a look now.
![bug veusz](https://cloud.githubusercontent.com/assets/27735649/25769226/145146ea-31ea-11e7-9f5a-5c1e7126671c.png)
