### ISSUE TITLE
Error Bar End Size

### ISSUE THREAD

**Issue by dolphiny21** [jeremysanders/veusz#56]
The error bar end size does not change, no matter what value is input into that control box.
![image](https://f.cloud.github.com/assets/6645575/2133359/30918dbc-92c2-11e3-9f26-cc71c192de13.png)

**Comment by kaberett** [comment]
As of now, I'm not seeing changes in barend size in the xy widget, for Veusz 1.21.1 under Debian 8 -- let me know if you'd like more info!

**Comment by KDB2** [comment]
You have a 2.5 years old version. 
You should grab the new one and install it. I know that the version in Debian repositories is 1.21.1, but there is now a 1.25 version.

**Comment by kaberett** [comment]
Turns out to have been my screw-up regardless; apologies for the incorrect report.
