### ISSUE TITLE
rounding with log axis

### ISSUE THREAD

**Issue by marcopigg** [jeremysanders/veusz#88]
I have an x axis going from 3000 to 10000. When ticking the 'Log' checkbox, the 'half' major tick, which should be 5000, is 4999. I can manually set the tick in the 'Major ticks' tab, but maybe some kind of rounding can be applied.

**Comment by jeremysanders** [comment]
I can't reproduce the 4999 issue. What version and platform are you using?

**Comment by marcopigg** [comment]
I am sorry. I have updated my veusz versions and cannot reproduce the issue as well, so I am closing it.
