### ISSUE TITLE
Zero-margins grid from script

### ISSUE THREAD

**Issue by brunetto** [jeremysanders/veusz#96]
Hi!
Is there a way to create a grid or set it to zero-margins from a python script? Or it can only be specified from the GUI?

**Comment by jeremysanders** [comment]
You can either:
* Manually set each graph margin to zero (i.e. left/right/top/bottomMargin)
* Change the default graph margins to zero, i.e. (with new style interface)
Root.StyleSheet.graph.leftMargin.val = '0cm'
Root.StyleSheet.graph.rightMargin.val = '0cm'
Root.StyleSheet.graph.topMargin.val = '0cm'
Root.StyleSheet.graph.bottomMargin.val = '0cm'
* Use the Action command to run the zero margin "action", i.e.
Action('zeroMargins', widget='/page1/grid1')
or
Root.page1.grid1.Action('zeroMargins')

**Comment by brunetto** [comment]
Perfect, the action command works!!
thanks!!!
